# Generated by Django 2.0.8 on 2018-11-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
