# Generated by Django 2.0.8 on 2018-11-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='app',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='bug_id',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='type',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
    ]
