# Generated by Django 2.0.8 on 2018-11-13 08:15

from django.db import migrations, models
import fileupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, null=True)),
                ('platform', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fileupload',
            name='pt_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='pubuser',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='app',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='bug_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to=fileupload.models.upload_to),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(default='-', help_text='上传文件名', max_length=200),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='platform',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='type',
            field=models.IntegerField(default='0', help_text='0 静态 1 全量war包 2 增量包 3 Jar包'),
        ),
    ]
