# Generated by Django 2.0.8 on 2018-11-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_auto_20181108_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='pubuser',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
