# Generated by Django 2.0.8 on 2018-11-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_fileupload_pubuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='pubuser',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
