# Generated by Django 2.0.1 on 2018-11-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('delivery_date', models.DateField(blank=True)),
                ('product_id', models.TextField()),
                ('payment_option', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='uploadlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('app', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=300)),
                ('bug_id', models.IntegerField()),
                ('file_path', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('upload_date', models.DateField()),
            ],
        ),
    ]
