# Generated by Django 2.0.1 on 2018-11-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='ipv4')),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(default='root', max_length=50)),
            ],
        ),
    ]
