# Generated by Django 2.0.8 on 2018-11-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(default='sobet', help_text='项目名称，如sobet，lottery，admin', max_length=100)),
                ('platform', models.CharField(default='', help_text='平台名称，如MC\\MD\\CYQ', max_length=100)),
                ('platform_cn', models.CharField(default='', help_text='中文名', max_length=100)),
                ('package_name', models.CharField(default='', help_text='合法包名，允许字段为空', max_length=100)),
                ('type', models.IntegerField(default='0', help_text='0 静态 1 全量war包 2 增量包 3 Jar包')),
                ('dst_file_path', models.CharField(default='', help_text='文件发布路径', max_length=200)),
                ('backup_file_dir', models.CharField(default='', max_length=200)),
                ('validate_user', models.CharField(default='', help_text='有权限发布的用户/用户组， 暂未使用', max_length=500)),
                ('ipaddress', models.ForeignKey(default='1', help_text='服务器IP地址', on_delete=django.db.models.deletion.CASCADE, to='cmdb.ServerInfo')),
            ],
        ),
    ]
