# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('package_name', models.CharField(max_length=100)),
                ('static_host', models.CharField(max_length=200)),
                ('static_dir', models.CharField(max_length=200)),
                ('validate_user', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RecordOfStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(auto_now=True)),
                ('isthis_current', models.CharField(max_length=300)),
                ('return_status', models.IntegerField(default=0)),
                ('deployment_user', models.CharField(max_length=50)),
                ('return_user', models.CharField(default='', max_length=50)),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontitems.ProjectInfo')),
            ],
        ),
    ]
