# Generated by Django 2.0.8 on 2018-11-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='server_ipaddress',
        ),
    ]
