# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-12 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordofstatic',
            old_name='package_name',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='recordofstatic',
            old_name='dtime',
            new_name='pub_time',
        ),
        migrations.RemoveField(
            model_name='recordofstatic',
            name='return_status',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='file_save_base_dir',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_cn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='package_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='static_dir',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='static_host',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='validate_user',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='recordofstatic',
            name='deployment_user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recordofstatic',
            name='isthis_current',
            field=models.BooleanField(default=False),
        ),
    ]
