# Generated by Django 2.0.8 on 2018-11-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0002_remove_projectinfo_server_ipaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordofstatic',
            old_name='upload_file',
            new_name='record_id',
        ),
        migrations.RemoveField(
            model_name='recordofstatic',
            name='dev_note',
        ),
        migrations.RemoveField(
            model_name='recordofstatic',
            name='isthis_current',
        ),
        migrations.RemoveField(
            model_name='recordofstatic',
            name='upload_user',
        ),
        migrations.RemoveField(
            model_name='recordofstatic',
            name='wait_pub',
        ),
        migrations.AddField(
            model_name='recordofstatic',
            name='pub_status',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='recordofstatic',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.ProjectInfo'),
        ),
        migrations.DeleteModel(
            name='ProjectInfo',
        ),
    ]
