# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-12 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0002_auto_20181012_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='backup_file_dir',
            field=models.CharField(default='', max_length=200),
        ),
    ]
