# Generated by Django 2.0.8 on 2018-11-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0003_auto_20181114_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordofstatic',
            name='platform',
            field=models.CharField(default='', max_length=50),
        ),
    ]
