# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-15 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0003_projectinfo_backup_file_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordofstatic',
            name='backuplist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recordofstatic',
            name='ignore_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordofstatic',
            name='newdir',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='recordofstatic',
            name='newfile',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
