# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0004_auto_20181015_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordofstatic',
            name='upload_file',
            field=models.CharField(default='', max_length=50),
        ),
    ]
