# Generated by Django 2.0.8 on 2018-11-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
        ('frontitems', '0005_recordofstatic_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordofstatic',
            old_name='deployment_user',
            new_name='pub_user',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='server_ipaddress',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cmdb.ServerInfo'),
        ),
        migrations.AddField(
            model_name='recordofstatic',
            name='dev_note',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='recordofstatic',
            name='upload_user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recordofstatic',
            name='wait_pub',
            field=models.BooleanField(default=True),
        ),
    ]
