# Generated by Django 2.0.8 on 2018-11-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0005_auto_20181114_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordofstatic',
            name='platform',
        ),
    ]
