# Generated by Django 2.0.8 on 2018-11-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0006_remove_recordofstatic_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordofstatic',
            name='record_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
