# Generated by Django 2.0.8 on 2018-11-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontitems', '0007_auto_20181115_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordofstatic',
            name='pub_filemd5sum',
            field=models.CharField(default='', max_length=50),
        ),
    ]
